lectures:
  label: Lecture

  displayed-links:
    - live_session_recordings
    - live_session_slides

  core-links:
    google-drive:
      icon: folder_shared
      label: live slides & recording
    webcast:
      icon: videocam
      label: video
    webcast_slides:
      icon: slideshow
      label: slides
    live_session_recording:
      icon: video_call
      label: live session recording
    live_session_slides:
      icon: slideshow
      label: live session slides
    resources:
      icon: folder_shared
      label: resources
  extra-links: []
  static-contents: []
    
labs:
  label: Lab
  displayed-links:
    - link
    - checkoff
  core-links:
    link:
      icon: computer
      label: webpage
    checkoff:
      icon: check_box
      label: checkoff
  extra-links: []
  static-contents: 
    - key: checkOffQuestions
      label: Check-Off Questions
      format: ul
  
discussion:
  label: Discussion
  displayed-links:
    - worksheet
    - solutions
  core-links:
    worksheet:
      icon: create
      label: worksheet
    solutions:
      icon: done_all
      label: solutions
    slides:
      icon: slideshow
      label: slides
    recording:
      icon: videocam
      label: recording
  extra-links:
    - key: resources
      label: Extra Resources
  static-contents: []

readings:
  label: Readings
  displayed-links: []
  core-links: {}
  extra-links:
    - key: readings
      label: Readings
  static-contents: []

projects:
  label: Project
  displayed-links:
    - spec
    - submit
  core-links:
    spec:
      icon: assignment
      label: spec
    submit:
      icon: publish
      label: submit
  extra-links:
    - key: resources
      label: Extra Resources
  static-contents: []
    