- label: Semester Calendar
  path: /semester
  
- label: Syllabus
  path: /syllabus

- label: Staff
  path: /staff

- label: Snap!
  path: "https://snap.berkeley.edu/snap/snap.html"

- label: Resources
  path: /resources

- label: Exams
  path: /exams