- label: CS10 Zoom
  link: "http://bjc.link/zoomroomsp21"
  icon: video_call

- label: Shannon's Tutoring
  link: "https://docs.google.com/forms/d/e/1FAIpQLSeCkNAmHN0NAq6KIXCdw1s_dW1QkNbc7LLRCKbyQcJIdALQVw/viewform?usp=sf_link"
  icon: video_call

- label: Discord
  link: "https://discord.gg/x64tYsrg6z"
  icon: exit_to_app

- label: "Gradescope: 6PGKWE"
  link: "https://www.gradescope.com/courses/224752"
  icon: spellcheck

- label: Piazza
  link: "https://piazza.com/class/kjt2jqnct3u2m"
  icon: supervisor_account