roles:
  - label: Professor
    people:
      - dan

  - label: Head TA
    people:
      - yolanda
      - shannon

  - label: TA
    people:
      - andrew
      - lam
      - bryant
      - dani
      - kellyann
  
  - label: Reader
    people:
      - samhita
      - sarah
      - taroob
  
  - label: Tutor
    people:
      - nick
      - gowri
      - vaibhav
      - deeksha
  
  - label: Academic Intern
    people:
      - aaronlee
      - aditisharma
      - alaynamatthews
      - angelrodriguez
      - annaclary
      - anthonylu
      - arrushiagarwal
      - benjaminpierias
      - charlottele
      - chloekim
      - danaipapaevgeniou
      - francisgeng
      - gautamanand
      - hyeonakim
      - jamescheng
      - jasonhuang
      - jaspershine
      - jeffreyhuang
      - jennguyen
      - jorgenunez
      - junyoungkim
      - justinflesher
      - kyawswaryemyint
      - madeleinefruman
      - madeleinelabute
      - manaarsalama
      - mannatjaggi
      - martingarcia-angel
      - mirandaaochi
      - monicacortes
      - nhuvu
      - paolanoun
      - pranavchhabra
      - randynguyen
      - rebeccahu
      - richeldhaliwal
      - rivkahbar-or
      - saadtootla
      - sarahtaylor
      - saruulamarbayar
      - yonsookim
      - sophiebrazdefaria
      - vedanshmalhotra
      - yishuchao

card-config:
  subheader: "pronouns"
  questions:
    - Where did you grow up? What was your path to Cal?
    - How much programming have you done? What languages?
    - What are your hobbies?
    - What are some of your talents and skills?
    - Have you done anything remarkable? Has anything memorable happened to you?
    - What commitments will be consuming your cycles this semester?